Repository elastic/apm-agent-rum-js, pull requests merged in 2019-12, with the labels that each got.

#507 ci(jenkins): cancel previous running builds
  Jenkinsfile
Labels: automation, ci

#512 [docs] RUM JS documentation restructure
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  docs/custom-transaction-name.asciidoc
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/opentracing.asciidoc
  docs/set-up.asciidoc
  docs/supported-technologies.asciidoc
Labels: docs

#508 chore(benchmarks): memory allocation per function during page-load [s…
  packages/rum/test/benchmarks/analyzer.js
  packages/rum/test/benchmarks/config.js
  packages/rum/test/benchmarks/profiler.js
  packages/rum/test/benchmarks/run.js
  packages/rum/test/benchmarks/server.js
Labels: [zube]: In Review

#523 [4.x][docs] Add placeholder changelog.asciidoc
  CHANGELOG.asciidoc
Labels: docs

#516 [docs] Build release notes to documentation
  CHANGELOG.asciidoc
  CHANGELOG.md
  docs/release-notes.asciidoc
Labels: blocked, docs

#457 chore: upgrade dev dependencies and fix flaky test
  dev-utils/karma.js
  dev-utils/test-utils.js
  package-lock.json
  package.json
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-react/test/specs/get-with-transaction.spec.js
  packages/rum/test/specs/apm-base.spec.js
  packages/rum/test/specs/index.spec.js
  scripts/license-checker.js
Labels: [zube]: In Review

#521 perf(rum-core): move unexposed configs inside constants to reduce bundlesize
  docs/configuration.asciidoc
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
Labels: [zube]: In Review

#528 chore(deps): upgrade build tools deps and fix security warnings
  dev-utils/build.js
  dev-utils/test-config.js
  docs/sourcemap.asciidoc
  package-lock.json
  package.json
  packages/rum/test/benchmarks/analyzer.js
  packages/rum/test/bundle/bundle.spec.js
  packages/rum/webpack.config.js
Labels: [zube]: In Review

#515 feat(rum-core): enrich span context with desination metadata
  packages/rum-core/src/common/context.js
  packages/rum-core/src/common/patching/fetch-patch.js
  packages/rum-core/src/common/url.js
  packages/rum-core/src/performance-monitoring/capture-navigation.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/span-base.js
  packages/rum-core/src/performance-monitoring/span.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/src/performance-monitoring/transaction.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/common/context.spec.js
  packages/rum-core/test/common/url.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-core/test/performance-monitoring/transaction.spec.js
Labels: [zube]: In Review

#538 [docs] Update build script
  scripts/build_docs.sh
Labels: docs

#539 chore(rum-core): tests for sending span destination context to server
  packages/rum-core/src/common/truncate.js
  packages/rum-core/test/common/truncate.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
Labels: [zube]: In Review

#541 chore(rum-core): add native URL parser tests aganist polyfill
  packages/rum-core/test/common/url.spec.js
Labels: [zube]: In Review

#544 docs: improve the page laod transaction instrumentation [skip ci]
  docs/intro.asciidoc
  docs/supported-technologies.asciidoc
Labels: docs
