Repository elastic/apm-agent-rum-js, pull requests merged in 2019-06, with the labels that each got.

#233 perf(rum-core): refactor error-logging & stack service to improve bundlesize
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/src/error-logging/index.js
  packages/rum-core/src/error-logging/stack-trace-service.js
  packages/rum-core/src/error-logging/stack-trace.js
  packages/rum-core/test/error-logging/stack-trace.spec.js
Labels: [zube]: In Review

#270 feat(rum): deprecate addTags in favor of addLabels
  docs/agent-api.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/utils.js
  packages/rum-core/src/opentracing/span.js
  packages/rum-core/src/performance-monitoring/span-base.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-core/test/common/utils.spec.js
  packages/rum-core/test/opentracing/opentracing.spec.js
  packages/rum-core/test/performance-monitoring/span-base.spec.js
  packages/rum/src/apm-base.js
  packages/rum/test/e2e/general-usecase/app.js
  packages/rum/test/specs/index.spec.js
Labels: [zube]: In Review

#271 chore(rum): enable extended debugging and console logs for e2e tests
  dev-utils/test-config.js
  packages/rum/run-script.js
  packages/rum/test/e2e/utils.js
Labels: [zube]: In Review

#273 fix(rum-core): capture all spans as part of page-load transaction
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/common/utils.js
  packages/rum-core/src/performance-monitoring/capture-hard-navigation.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/src/performance-monitoring/transaction.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
  packages/rum-core/test/performance-monitoring/transaction.spec.js
  packages/rum/test/e2e/general-usecase/app.e2e-spec.js
  packages/rum/test/e2e/manual-timing/app.js
Labels: [zube]: In Review, bug

#281 feat(rum-core): use error event instead of global onerror method
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/test/error-logging/error-logging.spec.js
Labels: [zube]: In Review

#278 chore(rum-core): remove functions from transaction-service
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/performance-monitoring/span-base.js
  packages/rum-core/src/performance-monitoring/span.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
Labels: [zube]: In Review

#287 chore(rum): fix release script
  RELEASE.md
  lerna.json
  package-lock.json
  package.json
  packages/rum-core/package.json
  packages/rum/package.json
  scripts/eslint-rules/version-checker.js
  scripts/github-release.js
  scripts/license-checker.js
  scripts/prompt-release.js
  scripts/publish-package.js
Labels: [zube]: In Review

#286 [docs][7.2] update environment config
  docs/configuration.asciidoc
Labels: docs

#274 fix(rum-core): remove sensitive info from span context
  packages/rum-core/src/common/url.js
  packages/rum-core/src/common/utils.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/test/common/url.spec.js
  packages/rum-core/test/common/utils.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
Labels: [zube]: In Review

#304 chore: use default name and type for transaction and spans
  packages/rum-core/src/performance-monitoring/span-base.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/performance-monitoring/span-base.spec.js
  packages/rum/src/apm-base.js
Labels: [zube]: In Review

#277 perf(rum-core): check span validition before creating arbitrary spans
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/performance-monitoring/capture-hard-navigation.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/test/performance-monitoring/capture-hard-navigation.spec.js
Labels: [zube]: Ready
