Repository elastic/apm-agent-rum-js, pull requests merged in 2019-04, with the labels that each got.

#236 fix(rum-core): hardcode agent name and version in service metadata
  dev-utils/karma.js
  dev-utils/test-config.js
  package-lock.json
  package.json
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum/babel-version-plugin.js
  packages/rum/package.json
  packages/rum/src/apm-base.js
  packages/rum/webpack.config.js
Labels: [zube]: In Review, bug

#239 fix(rum): return noop agent when config is inactive
  docs/agent-api.asciidoc
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/service-factory.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum/src/apm-base.js
  packages/rum/test/specs/apm-base.spec.js
Labels: [zube]: In Review

#232 [docs] CORS documentation
  docs/intro.asciidoc
Labels: docs

#250 [docs] Update source map documentation
  docs/sourcemap.asciidoc
Labels: docs

#241 fix(rum-core): apply truncation on keyword fields in payload
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/common/truncate.js
  packages/rum-core/src/common/utils.js
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-core/test/common/truncate.spec.js
  packages/rum-core/test/common/utils.spec.js
  packages/rum-core/test/error-logging/error-logging.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
Labels: [zube]: In Review
