Repository elastic/apm-agent-rum-js, pull requests merged in 2019-10, with the labels that each got.

#445 [docs] Fix build script
  scripts/build_docs.sh
Labels: docs

#446 fix(rum-core): handle relative urls without slash properly
  packages/rum-core/src/common/url.js
  packages/rum-core/test/common/url.spec.js
Labels: [zube]: In Review

#449 fix(rum-angular): use explicit angular injection for service
  docs/angular-integration.asciidoc
  packages/rum-angular/src/apm-service.ts
  packages/rum-angular/test/e2e/with-router/app/app.module.ts
Labels: [zube]: In Review

#442 chore(docs): add note about unmanaged transactions
  docs/agent-api.asciidoc
  docs/custom-transactions.asciidoc
Labels: [zube]: In Progress

#454 ci(jenkins): reuse agents (2 less agents to be used)
  Jenkinsfile
Labels: automation, ci

#456 ci(jenkins): benchmark in a bare metal
  .ci/scripts/benchmarks.sh
  .ci/scripts/test.sh
  Jenkinsfile
  dev-utils/docker-compose.yml
  package.json
  packages/rum-core/test/benchmarks/performance-monitoring.bench.js
  scripts/benchmarks.js
Labels: automation, ci

#458 feat(rum-core): copy transaction context info to error
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/test/error-logging/error-logging.spec.js
Labels: [zube]: In Review

#438 feat(rum-core): move breakdown algorithm post transaction finish
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/utils.js
  packages/rum-core/src/performance-monitoring/breakdown.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/span-base.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/src/performance-monitoring/transaction.js
  packages/rum-core/test/performance-monitoring/breakdown.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
  packages/rum-core/test/performance-monitoring/transaction.spec.js
Labels: [zube]: In Review

#439 feat(rum-core): use etag for fetching config
  dev-utils/test-servers.js
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/constants.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum/test/specs/apm-base.spec.js
Labels: [zube]: In Progress

#466 docs: Add Central Config documentation
  docs/configuration.asciidoc
Labels: [zube]: In Review

#464 feat(rum-core): align breakdown types based on navigation timing
  packages/rum-core/src/performance-monitoring/breakdown.js
  packages/rum-core/test/fixtures/navigation-entries.js
  packages/rum-core/test/performance-monitoring/breakdown.spec.js
  packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
Labels: [zube]: In Review
