Repository elastic/apm-agent-rum-js, pull requests merged in 2019-08, with the labels that each got.

#368 [docs] Add supported platforms image
  docs/images/compatibility.png
  docs/supported-technologies.asciidoc
Labels: docs

#373 chore(release): clean dist folder before preparing release
  package.json
Labels: [zube]: In Review

#378 [docs] Remove js-base from documentation
  CHANGELOG.md
  README.md
  docs/index.asciidoc
  package.json
  packages/rum-core/README.md
  packages/rum-react/README.md
  packages/rum-react/package.json
  packages/rum/README.md
Labels: docs

#302 chore(benchmark): measure impact of rum agent during page load
  package-lock.json
  package.json
  packages/rum-core/karma.bench.conf.js
  packages/rum-core/package.json
  packages/rum/package.json
  packages/rum/test/benchmarks/analyzer.js
  packages/rum/test/benchmarks/config.js
  packages/rum/test/benchmarks/pages/basic.ejs
  packages/rum/test/benchmarks/pages/head.ejs
  packages/rum/test/benchmarks/pages/heavy.ejs
  packages/rum/test/benchmarks/pages/init.ejs
  packages/rum/test/benchmarks/profiler.js
  packages/rum/test/benchmarks/run.js
  packages/rum/test/benchmarks/server.js
  scripts/benchmarks.js
Labels: [zube]: In Review

#381 chore(benchmark): add parse and exec time metrics to benchmark
  packages/rum/test/benchmarks/analyzer.js
  packages/rum/test/benchmarks/config.js
  packages/rum/test/benchmarks/pages/head.ejs
  packages/rum/test/benchmarks/pages/init.ejs
  packages/rum/test/benchmarks/profiler.js
  packages/rum/test/benchmarks/run.js
  packages/rum/test/benchmarks/server.js
Labels: [zube]: In Review

#388 [docs][4.x] Update link to APM server
  docs/intro.asciidoc
Labels: docs

#387 [docs] Update link to APM server
  docs/intro.asciidoc
Labels: docs

#382 fix(rum): log unsupported message only on browser environment
  packages/rum/src/bootstrap.js
  packages/rum/test/node/index-export.spec.js
  packages/rum/test/node/opentracing-export.spec.js
  packages/rum/test/specs/index.spec.js
Labels: [zube]: In Review

#391 ci(jenkins): avoid using the any agent to skip running in the master-worker
  Jenkinsfile
Labels: automation, ci, enhancement

#393 ci(jenkins): Fix environment variable used to calculate git commit
  Jenkinsfile
Labels: automation, bug, ci

#398 ci(jenkins): revert none agent
  Jenkinsfile
Labels: automation, ci

#392 fix(rum-react): respect active flag in react integration
  packages/rum-react/src/get-with-transaction.js
  packages/rum-react/test/specs/get-apm-route.spec.js
  packages/rum-react/test/specs/get-with-transaction.spec.js
Labels: [zube]: In Review
