Repository elastic/apm-agent-rum-js, pull requests merged in 2019-02, with the labels that each got.

#165 chore: use object shorthand notation in eslint rules
  .eslintrc.js
  dev-utils/karma.js
  dev-utils/test.js
  packages/rum-core/karma.bench.conf.js
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/patching/fetch-patch.js
  packages/rum-core/src/common/patching/xhr-patch.js
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/src/error-logging/index.js
  packages/rum-core/src/index.js
  packages/rum-core/src/performance-monitoring/index.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-core/test/common/throttle.spec.js
  packages/rum-core/test/common/utils.spec.js
  packages/rum-core/test/index.js
  packages/rum-core/test/utils/apm-server-mock.js
  packages/rum-core/test/utils/transportMock.js
  packages/rum/run-script.js
  packages/rum/src/index.js
  packages/rum/test/e2e/integration-test.js
  packages/rum/test/e2e/sourcemap/test-sourcemap.js
  packages/rum/test/node/upload-sourcemaps.node-spec.js
  packages/rum/wdio.conf.js
  test.config.js
Labels: [zube]: In Review

#171 chore: publish individual packages via lerna
  README.md
  RELEASE.md
  lerna.json
  package.json
  scripts/publish.js
Labels: [zube]: In Review

#166 chore: fix release script for github artificats
  package.json
  packages/rum/package.json
  scripts/release-github.js
Labels: [zube]: In Review

#173 feat(rum-core): measure all resource entries in page load
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/performance-monitoring/capture-hard-navigation.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/fixtures/navigation-timing-span-snapshot.js
  packages/rum-core/test/fixtures/resource-entries.js
  packages/rum-core/test/performance-monitoring/capture-hard-navigation.spec.js
Labels: [zube]: In Review, enhancement

#178 chore: modify notice generation script [skip ci]
  .gitignore
  dev-utils/dep-info.js
  packages/rum-core/NOTICE.txt
  packages/rum-core/README.md
  packages/rum/NOTICE.txt
Labels: [zube]: In Review

#154 chore: run bundlesize check during build
  .travis.yml
  package-lock.json
  package.json
  packages/rum/package.json
  scripts/license-checker.js
Labels: [zube]: In Review

#184 docs: add more workflow sections to contributing.md
  CONTRIBUTING.md
Labels: [zube]: In Review

#186 chore: add repository.directory field to package.json[skip ci]
  packages/rum-core/package.json
  packages/rum/package.json
Labels: [zube]: In Review

#188 chore: add readmes for individual packages
  README.md
  packages/rum-core/README.md
  packages/rum/README.md
Labels: [zube]: In Review

#185 chore: root level lock files with relative path specifiers
  .travis.yml
  RELEASE.md
  package-lock.json
  package.json
  packages/rum-core/karma.conf.js
  packages/rum-core/package-lock.json
  packages/rum-core/package.json
  packages/rum/package-lock.json
  packages/rum/package.json
  scripts/license-checker.js
Labels: [zube]: In Review

#174 perf(rum-core): avoid url parsing on resource timing entries
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/performance-monitoring/capture-hard-navigation.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/transaction.js
Labels: [zube]: In Review, performance
