Repository elastic/apm-agent-rum-js, pull requests merged in 2019-07, with the labels that each got.

#216 feat(rum): better log message on invalid configuration
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-core/test/common/utils.spec.js
  packages/rum-core/test/error-logging/error-logging.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum/src/apm-base.js
  packages/rum/test/specs/apm-base.spec.js
  packages/rum/test/specs/index.spec.js
Labels: [zube]: In Review

#276 feat(rum-core): add user timing spans to the page-load transaction
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/performance-monitoring/capture-hard-navigation.js
  packages/rum-core/test/fixtures/user-timing-entries.js
  packages/rum-core/test/performance-monitoring/capture-hard-navigation.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
  packages/rum-core/test/utils/globals-mock.js
Labels: [zube]: In Review

#306 chore(rum-core): fix benchmark karma runner script [skip ci]
  package-lock.json
  package.json
  packages/rum-core/karma.bench.conf.js
  packages/rum-core/test/benchmarks/001-performance-monitoring.bench.js
  packages/rum-core/test/benchmarks/index.js
Labels: [zube]: In Review

#245 perf(rum): remove debug logs on production build
  dev-utils/test-config.js
  docs/intro.asciidoc
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/env.js
  packages/rum-core/src/opentracing/tracer.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum/webpack.config.js
Labels: [zube]: In Review, performance

#299 chore: add chrome 74 to e2e test
  dev-utils/test-config.js
  packages/rum-core/test/common/fetch-patch.spec.js
Labels: [zube]: In Review

#312 chore: optimise the testing workflow based on the mode set
  CONTRIBUTING.md
  RELEASE.md
  dev-utils/integration-test.js
  dev-utils/run-script.js
  dev-utils/test-servers.js
  dev-utils/test-utils.js
  package-lock.json
  package.json
  packages/rum-core/package.json
  packages/rum-react/package.json
  packages/rum/package.json
  packages/rum/run-script.js
  packages/rum/test/integration/babel.helper.js
Labels: [zube]: In Review

#316 fix(rum:core): send labels via context.tags in the payload
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/performance-monitoring/span-base.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-core/test/opentracing/opentracing.spec.js
  packages/rum-core/test/performance-monitoring/span-base.spec.js
Labels: [zube]: In Review

#180 ci(jenkins): RUM agent pipeline
  .ci/.jenkins_scope.yaml
  .ci/.jenkins_stack_versions.yaml
  .ci/docker/node-puppeteer/Dockerfile
  .ci/scripts/lint.sh
  .ci/scripts/test.sh
  .travis.yml
  Jenkinsfile
  dev-utils/docker-compose.yml
  dev-utils/karma.js
  dev-utils/test-config.js
  packages/rum-react/test/e2e/react/index.html
Labels: [zube]: In Review, automation

#324 ci(jenkins): more resilient when infra is temporarily unreachable
  .ci/scripts/pull_and_build.sh
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#326 ci(jenkins): ITs for forked repos with different name is not supported
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#323 ci(jenkins): enable junit reporting to be consumed by the pipeline
  Jenkinsfile
  dev-utils/karma.js
  package-lock.json
  package.json
Labels: [zube]: In Review, automation, ci

#332 ci(jenkins): report cobertura in the pipeline
  Jenkinsfile
  dev-utils/docker-compose.yml
  dev-utils/karma.js
Labels: [zube]: In Progress, automation, ci, enhancement

#336 chore(codecov): fix coverage report issues
  codecov.yml
Labels: [zube]: In Review

#325 chore(benchmarks): run benchmarks and store results in cluster
  .ci/scripts/benchmarks.sh
  Jenkinsfile
  dev-utils/docker-compose.yml
  dev-utils/test-config.js
  package-lock.json
  package.json
  packages/rum-core/karma.bench.conf.js
  packages/rum-core/package.json
  packages/rum-core/test/benchmarks/performance-monitoring.bench.js
  packages/rum-core/test/benchmarks/transaction-service.bench.js
  scripts/benchmarks.js
Labels: [zube]: In Review

#337 fix(rum-core): check ignoreTransactions config value
  packages/rum-core/src/performance-monitoring/transaction-service.js
Labels: [zube]: In Review

#338 ci(jenkins): retry in case some enviromental issues
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#330 feat(rum-core): improver error message on payload failure
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/common/fetch-patch.spec.js
Labels: [zube]: In Review

#345 ci: docs stage is handled within the elasticsearch-ci/docs
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#356 feat(rum-react): publish traspiled react elements as es modules
  dev-utils/build.js
  packages/rum-react/babel.config.js
  packages/rum-react/package.json
Labels: [zube]: In Review

#358 chore(karma): watch files in dev and run individual tests
  CONTRIBUTING.md
  dev-utils/karma.js
  dev-utils/test-config.js
  package-lock.json
  package.json
  packages/rum-core/karma.bench.conf.js
  packages/rum-core/karma.conf.js
  packages/rum-core/package.json
  packages/rum-core/test/benchmarks/performance-monitoring.bench.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/error-logging/error-logging.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-react/karma.conf.js
  packages/rum-react/package.json
  packages/rum/karma.conf.js
  packages/rum/package.json
  packages/rum/test/e2e/index.js
  packages/rum/test/e2e/standalone-html/opentracing.js
  packages/rum/test/integration/index.spec.js
  packages/rum/test/specs/index.spec.js
Labels: [zube]: In Review
