Repository elastic/apm-agent-rum-js, pull requests merged in 2019-03, with the labels that each got.

#198 feat(rum-core): add service env to metadata payload
  docs/configuration.asciidoc
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/utils.js
  packages/rum-core/test/common/apm-server.spec.js
Labels: [zube]: In Review

#201 chore(rum): e2e bundles should point to correct apm server url
  dev-utils/test-config.js
Labels: [zube]: In Review

#200 chore: rename references to the github repo
  CONTRIBUTING.md
  README.md
  docs/intro.asciidoc
  docs/troubleshooting.asciidoc
  package.json
  packages/rum-core/package.json
  packages/rum/package.json
  packages/rum/test/e2e/general-usecase/app.js
  packages/rum/test/e2e/react/rum.js
  packages/rum/test/node/upload-sourcemaps.node-spec.js
  scripts/release-github.js
Labels: [zube]: In Review

#179 BREAKING CHANGE(rum): resolve main field to source file
  packages/rum/package.json
Labels: [zube]: In Review

#207 Update changelog 4.0.0 [skip ci]
  CHANGELOG.md
  packages/rum-core/CHANGELOG.md
  packages/rum/CHANGELOG.md
Labels: [zube]: In Review

#208 chore(rum): unhandled promise rejection in integration test
  packages/rum/run-script.js
  packages/rum/test/e2e/integration-test.js
  packages/rum/test/node/integration-test.node-spec.js
Labels: [zube]: In Review

#212 chore: fix e2e tests and migrate to webdriver 5
  dev-utils/karma.js
  dev-utils/test-utils.js
  dev-utils/webdriver.js
  package-lock.json
  package.json
  packages/rum/run-script.js
  packages/rum/test/e2e/general-usecase/app.e2e-spec.js
  packages/rum/test/e2e/manual-timing/app.e2e-spec.js
  packages/rum/test/e2e/react/app.e2e-spec.js
  packages/rum/test/e2e/standalone-html/app.e2e-failsafe.js
  packages/rum/test/e2e/standalone-html/app.e2e-spec.js
  packages/rum/wdio-failsafe.conf.js
  packages/rum/wdio.conf.js
Labels: [zube]: In Review

#229 (docs): update api docs for Agent, Transaction and Span
  docs/agent-api.asciidoc
  docs/api.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
Labels: [zube]: In Review

#227 chore(rum): update browser versions for android and ios in tests
  dev-utils/karma.js
  dev-utils/test-config.js
  dev-utils/webdriver.js
  packages/rum-core/test/common/fetch-patch.spec.js
  packages/rum-core/test/common/patch.js
  packages/rum/test/e2e/general-usecase/app.js
  packages/rum/test/e2e/manual-timing/app.e2e-spec.js
  packages/rum/test/e2e/react/app.e2e-spec.js
  packages/rum/test/e2e/react/app.jsx
  packages/rum/test/e2e/react/main-component.jsx
  packages/rum/test/e2e/react/webpack.config.js
  packages/rum/wdio-failsafe.conf.js
  packages/rum/wdio.conf.js
Labels: [zube]: In Review

#203 Just a little typo thing to make the example work
  docs/custom-transaction-name.asciidoc
Labels: [zube]: In Review, docs

#234 chore(rum): print browser logs only on e2e test failures
  packages/rum/wdio.conf.js
Labels: [zube]: In Review

#235 [docs] Add release notes
  docs/index.asciidoc
  docs/release-notes.asciidoc
Labels: docs
