Repository elastic/apm-agent-rum-js, pull requests merged in 2019-09, with the labels that each got.

#403 chore(saucelabs): fix script timeout issues in saucelabs
  .travis.yml
  dev-utils/build.js
  dev-utils/webdriver.js
  packages/rum-react/test/e2e/with-router/general.e2e-spec.js
  packages/rum-react/test/e2e/with-router/switch.e2e-spec.js
  packages/rum-react/test/e2e/with-router/webpack.config.js
Labels: [zube]: In Review

#384 feat(rum): angular integration with apm-rum
  .ci/.jenkins_scope.yaml
  .eslintrc.js
  .travis.yml
  dev-utils/build.js
  dev-utils/karma.js
  dev-utils/test-utils.js
  dev-utils/webdriver.js
  package-lock.json
  package.json
  packages/rum-angular/NOTICE.txt
  packages/rum-angular/README.md
  packages/rum-angular/babel.config.js
  packages/rum-angular/karma.conf.js
  packages/rum-angular/package.json
  packages/rum-angular/src/apm-service.ts
  packages/rum-angular/src/index.ts
  packages/rum-angular/test/e2e/with-router/app.e2e-spec.js
  packages/rum-angular/test/e2e/with-router/app/app.component.ts
  packages/rum-angular/test/e2e/with-router/app/app.module.ts
  packages/rum-angular/test/e2e/with-router/app/app.routing.module.ts
  packages/rum-angular/test/e2e/with-router/app/contact-detail.component.ts
  packages/rum-angular/test/e2e/with-router/app/contact-list.component.ts
  packages/rum-angular/test/e2e/with-router/app/contact.service.ts
  packages/rum-angular/test/e2e/with-router/app/home.component.ts
  packages/rum-angular/test/e2e/with-router/app/not-found.component.ts
  packages/rum-angular/test/e2e/with-router/data.json
  packages/rum-angular/test/e2e/with-router/index.html
  packages/rum-angular/test/e2e/with-router/main.ts
  packages/rum-angular/test/e2e/with-router/webpack.config.js
  packages/rum-angular/test/index.ts
  packages/rum-angular/test/polyfills.ts
  packages/rum-angular/test/specs/apm-service.spec.ts
  packages/rum-angular/wdio.conf.js
Labels: [zube]: In Review

#397 docs(angular): add angular framework integration document
  docs/angular-integration.asciidoc
  docs/framework-integrations.asciidoc
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review, docs

#406 ci(jenkins): Set GitHub notification context to apm-ci
  .ci/jobs/defaults.yml
Labels: automation, ci

#409 chore(travis): run packages tests only on single stack
  .travis.yml
Labels: [zube]: In Review

#414 fix(rum-angular): proper transaction name for lazy loaded routes
  packages/rum-angular/src/apm-service.ts
  packages/rum-angular/test/specs/apm-service.spec.ts
Labels: [zube]: In Review

#418 fix(rum-core): handle script error events properly
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/test/error-logging/error-logging.spec.js
Labels: [zube]: In Review

#419 fix(rum-core): create transaction only on component mount
  packages/rum-react/src/get-with-transaction.js
  packages/rum-react/test/specs/get-with-transaction.spec.js
Labels: [zube]: In Review

#430 [2.x] docs: update moved secret token link
  docs/sourcemap.asciidoc
Labels: docs

#429 [3.x] docs: update moved secret token link
  docs/sourcemap.asciidoc
Labels: docs

#428 [4.x] docs: update moved secret token link
  docs/sourcemap.asciidoc
Labels: docs

#431 docs: update moved secret token link
  docs/sourcemap.asciidoc
Labels: docs

#415 feat: Support central config management
  .travis.yml
  CONTRIBUTING.md
  dev-utils/build.js
  dev-utils/docker-compose.yml
  dev-utils/karma.js
  dev-utils/run-script.js
  dev-utils/test-config.js
  dev-utils/test-servers.js
  package-lock.json
  package.json
  packages/rum-core/package.json
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-react/package.json
  packages/rum/package.json
  packages/rum/src/apm-base.js
  packages/rum/test/specs/apm-base.spec.js
Labels: [zube]: In Progress

#374 chore(notice): generate notice based on dependency graph
  dev-utils/dep-info.js
  packages/rum-react/NOTICE.txt
Labels: [zube]: In Review, dev

#424 refactor(rum-core): remove capturePageLoad and sendPageLoadTransaction flag
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/utils.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
  packages/rum/src/apm-base.js
  packages/rum/test/e2e/manual-timing/app.js
  packages/rum/test/specs/apm-base.spec.js
Labels: [zube]: In Review

#412 feat(rum-core): breakdown graphs for transaction
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/utils.js
  packages/rum-core/src/performance-monitoring/breakdown.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/span-base.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/src/performance-monitoring/transaction.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/fixtures/navigation-entries.js
  packages/rum-core/test/performance-monitoring/breakdown.spec.js
  packages/rum-core/test/performance-monitoring/capture-hard-navigation.spec.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
  packages/rum-core/test/utils/globals-mock.js
Labels: [zube]: In Review

#423 feat(rum-core): capture resource and user timing spans for soft navigation
  dev-utils/webdriver.js
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/performance-monitoring/capture-navigation.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/src/performance-monitoring/transaction.js
  packages/rum-core/test/fixtures/user-timing-entries.js
  packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
  packages/rum-react/test/e2e/components/manual-component.js
  packages/rum-react/test/e2e/with-router/general.e2e-spec.js
  packages/rum-react/test/e2e/with-router/general.js
Labels: [zube]: In Review

#443 fix: change codecov report setting
  codecov.yml
Labels: automation, ci

#432 fix(rum): publish all packages as transpiled modules
  dev-utils/build.js
  dev-utils/karma.js
  dev-utils/run-script.js
  package-lock.json
  package.json
  packages/rum-angular/package.json
  packages/rum-core/babel.config.js
  packages/rum-core/package.json
  packages/rum-react/package.json
  packages/rum-react/test/e2e/index.js
  packages/rum-react/test/e2e/with-router/webpack.config.js
  packages/rum/babel.config.js
  packages/rum/package.json
  packages/rum/test/bundle/bundle.spec.js
Labels: [zube]: In Review

#427 feat(rum-core): capture unhandled promise rejection as errors
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/test/error-logging/error-logging.spec.js
  packages/rum/src/apm-base.js
  packages/rum/test/specs/apm-base.spec.js
Labels: [zube]: In Review
