Repository elastic/apm-agent-rum-js, pull requests merged in 2020-07, with the labels that each got.

#793 ci: post-release task to upload to CDN
  .ci/scripts/index.html.template
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#839 ci: run linting always
  Jenkinsfile
Labels: automation, ci

#852 docs: disable agent
  docs/troubleshooting.asciidoc
Labels: docs
