Repository elastic/apm-agent-rum-js, pull requests merged in 2020-03, with the labels that each got.

#542 ci: enable SauceLab test on Jenkins only
  .ci/docker/node-puppeteer/Dockerfile
  .ci/docker/node-puppeteer/run-test.sh
  .ci/scripts/test.sh
  .travis.yml
  Jenkinsfile
  dev-utils/docker-compose.yml
  dev-utils/karma.js
  scripts/export-saucelabs-account
Labels: [zube]: In Review, automation, ci

#673 ci: collect JUnit results
  Jenkinsfile
Labels: automation, ci

#548 BREAKING CHANGE: change agent name to rum-js
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/test/common/apm-server.spec.js
Labels: breaking change

#626 BREAKING CHANGE: use the official traceparent header
  dev-utils/test-servers.js
  packages/rum-core/src/common/config-service.js
Labels: breaking change

#670 BREAKING CHANGE(rum-core): remove debug config in favor of logLevel
  packages/rum-angular/test/e2e/with-router/app/app.module.ts
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/service-factory.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-core/test/common/service-factory.spec.js
  packages/rum-react/test/e2e/with-router/general.js
  packages/rum-react/test/e2e/with-router/switch.js
  packages/rum-vue/test/e2e/app.js
  packages/rum/test/e2e/general-usecase/app.js
Labels: breaking change

#697 BREAKING CHANGE: add support for boolean and number values in addLabels
  packages/rum-core/src/common/utils.js
  packages/rum-core/test/common/config-service.spec.js
  packages/rum-core/test/common/utils.spec.js
Labels: breaking change

#696 BREAKING CHANGE: remove addTags method
  packages/rum-core/src/performance-monitoring/span-base.js
  packages/rum/src/apm-base.js
Labels: breaking change

#694 [docs] Add upgrading to 5.x guide
  docs/configuration.asciidoc
  docs/distributed-tracing-guide.asciidoc
  docs/upgrading.asciidoc
Labels: docs

#664 BREAKING CHANGE(rum-core): process all events in a single queue for reporting
  dev-utils/integration-test.js
  dev-utils/webdriver.js
  packages/rum-angular/test/e2e/with-router/app.e2e-spec.js
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/common/queue.js
  packages/rum-core/src/common/throttle.js
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/test/common/apm-server.spec.js
  packages/rum-core/test/common/throttle.spec.js
  packages/rum-core/test/error-logging/error-logging.spec.js
  packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
  packages/rum-core/test/utils/apm-server-mock.js
  packages/rum-core/test/utils/subscription.js
  packages/rum-react/package.json
  packages/rum-react/test/e2e/with-router/general.e2e-spec.js
  packages/rum-react/test/e2e/with-router/switch.e2e-spec.js
  packages/rum-vue/test/e2e/app.e2e-spec.js
  packages/rum/test/e2e/general-usecase/app.e2e-spec.js
  packages/rum/test/e2e/manual-timing/app.e2e-spec.js
  packages/rum/test/specs/index.spec.js
Labels: breaking change

#704 ci(jenkins): enable lint commit
  .ci/scripts/lint.sh
  package-lock.json
  package.json
  scripts/lint-commits.sh
Labels: automation, ci, enhancement

#709 ci(jenkins): enhance commit linting
  package.json
  scripts/lint-commits.sh
Labels: automation

#711 docs: add link to 5.x release notes
  docs/release-notes.asciidoc
Labels: docs

#712 docs: add link to 5.x release notes (#711)
  docs/release-notes.asciidoc
Labels: docs

#710 docs: add link to dot net repo
  docs/distributed-tracing-guide.asciidoc
Labels: docs

#716 ci(jenkins): speed up builds with only docs changes
  Jenkinsfile
Labels: automation, ci, enhancement

#717 ci(jenkins): pull request title linting validation
  scripts/lint-commits.sh
Labels: automation, ci

#725 docs: Add link to Agent/Server compatibility
  docs/intro.asciidoc
Labels: docs

#728 ci(jenkins): apm-its disabled when docs
  Jenkinsfile
Labels: [zube]: In Review, automation
