Repository elastic/apm-agent-rum-js, pull requests merged in 2020-01, with the labels that each got.

#537 feat(rum): add typescript typings
  .eslintrc.js
  dev-utils/karma.js
  docs/advanced-topics.asciidoc
  packages/rum/package.json
  packages/rum/src/index.d.ts
  packages/rum/test/types/index.spec.ts
  packages/rum/test/types/tsconfig.json
Labels: [zube]: In Review

#564 docs(rum): Benchmark metrics explanation doc
  packages/rum/test/benchmarks/BENCHMARKS.md
Labels: docs

#569 fix(rum): noop for API when agent is inactive
  packages/rum/src/apm-base.js
  packages/rum/test/specs/apm-base.spec.js
Labels: [zube]: In Review

#573 [docs] fix broken doc build script
  CHANGELOG.asciidoc
  package.json
  scripts/build_docs.sh
Labels: docs

#585 fix(rum-core): avoid firing transaction-start event on reused transactions
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
Labels: [zube]: In Review

#591 chore(rum-vue): remove vue-router from peer dependencies
  packages/rum-vue/package.json
Labels: [zube]: In Review

#590 fix(rum-core): do not capture timing spans for unsampled transactions
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
Labels: [zube]: In Review

#592 test: allow to disable certificates verification on ITs
  dev-utils/integration-test.js
Labels: automation, ci

#586 fix(rum-core): add error properties to custom context by default
  packages/rum-core/src/error-logging/error-logging.js
  packages/rum-core/test/error-logging/error-logging.spec.js
Labels: [zube]: In Review

#581 feat(rum-core): capture long tasks and lcp using performance observer
  packages/rum-core/src/common/constants.js
  packages/rum-core/src/common/context.js
  packages/rum-core/src/common/utils.js
  packages/rum-core/src/performance-monitoring/breakdown.js
  packages/rum-core/src/performance-monitoring/capture-navigation.js
  packages/rum-core/src/performance-monitoring/perf-entry-recorder.js
  packages/rum-core/src/performance-monitoring/performance-monitoring.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/common/utils.spec.js
  packages/rum-core/test/fixtures/lcp-entries.js
  packages/rum-core/test/fixtures/longtask-entries.js
  packages/rum-core/test/performance-monitoring/perf-entry-recorder.spec.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
  packages/rum-core/test/utils/globals-mock.js
Labels: [zube]: In Review
