Repository elastic/apm-agent-rum-js, pull requests merged in 2020-04, with the labels that each got.

#735 ci(jenkins): comparator is not needed
  Jenkinsfile
Labels: automation, ci

#602 ci(jenkins): support release automation
  .ci/scripts/prepare-git-context.sh
  Jenkinsfile
  RELEASE.md
  package-lock.json
  package.json
  scripts/prompt-release.js
Labels: [zube]: In Review, automation, ci, enhancement

#743 chore(release): update changelog for last release
  packages/rum-angular/CHANGELOG.md
  packages/rum-core/CHANGELOG.md
  packages/rum-react/CHANGELOG.md
  packages/rum-vue/CHANGELOG.md
  packages/rum/CHANGELOG.md
Labels: [zube]: In Review, automation, bug

#744 ci(jenkins): release automation followups
  .ci/scripts/prepare-git-context.sh
  Jenkinsfile
  RELEASE.md
  lerna.json
Labels: [zube]: In Review, automation, bug, ci, docs

#756 ci(jenkins): refactor with withGitRelease step
  .ci/scripts/prepare-git-context.sh
  Jenkinsfile
Labels: automation, ci

#770 docs: add missing distributed tracing setup links
  docs/distributed-tracing-guide.asciidoc
Labels: docs

#769 docs: simplify source map docs
  docs/sourcemap.asciidoc
Labels: docs
