Repository elastic/apm-agent-rum-js, pull requests merged in 2020-02, with the labels that each got.

#599 ci: ignoreHTTPSErrors check condition is inverted
  dev-utils/integration-test.js
Labels: automation, bug, ci

#597 docs: interpreting longtasks as spans
  docs/advanced-topics.asciidoc
Labels: [zube]: In Review

#605 ci(jenkins): less verbose console output
  .ci/scripts/pull_and_build.sh
  .ci/scripts/test.sh
Labels: automation, ci

#600 feat(rum-core): add config option to monitor longtasks
  docs/configuration.asciidoc
  packages/rum-core/src/common/config-service.js
  packages/rum-core/src/performance-monitoring/transaction-service.js
  packages/rum-core/test/performance-monitoring/transaction-service.spec.js
Labels: [zube]: In Review

#593 chore(benchmark): run benchmarks on chromium, firefox and webkit
  package-lock.json
  package.json
  packages/rum-core/karma.bench.conf.js
  packages/rum/test/benchmarks/analyzer.js
  packages/rum/test/benchmarks/config.js
  packages/rum/test/benchmarks/profiler.js
  packages/rum/test/benchmarks/run.js
  scripts/benchmarks.js
Labels: [zube]: In Review

#611 docs: Fix release build
  docs/sourcemap.asciidoc
Labels: docs

#616 fix: pass correct properties to payload filters
  packages/rum-core/src/common/apm-server.js
  packages/rum-core/test/common/apm-server.spec.js
Labels: bug

#632 [docs] Improve distributed tracing documentation
  docs/distributed-tracing-guide.asciidoc
Labels: docs

#631 [docs] Add EOL table
  RELEASE.md
  docs/index.asciidoc
  docs/upgrading.asciidoc
Labels: docs

#641 ci(jenkins): test pipeline optimisation
  Jenkinsfile
Labels: automation, ci

#653 ci(jenkins): enable benchmark for PRs if changes in the benchmark files
  Jenkinsfile
Labels: automation, ci

#659 ci(jenkins): benchmark fails with playwright in the CI
  Jenkinsfile
Labels: automation, ci

#663 ci(jenkins): apm-its-downstream params has changed
  Jenkinsfile
Labels: automation
