Repository elastic/apm-agent-rum-js, pull requests merged in 2020-06, with the labels that each got.

#807 fix: workaround for elastic/beats#18858
  dev-utils/docker-compose.yml
Labels: [zube]: In Review, automation, bug, ci

#809 fix: env var invalid type
  dev-utils/docker-compose.yml
Labels: automation, bug

#810 ci: use dockerLogs step
  Jenkinsfile
Labels: automation, ci

#812 ci: run benchmark on a PR basis if comment
  Jenkinsfile
Labels: automation, ci

#826 ci(jenkins): report bundlesize as a GitHub comment
  Jenkinsfile
Labels: automation, ci
