Repository elastic/apm-agent-rum-js, pull requests merged in 2021-06, with the labels that each got.

#1038 ci: bump elastic stack version
  .ci/bump-stack-release-version.sh
  .ci/scripts/load-testing.sh
  .ci/scripts/pull_and_build.sh
  .ci/scripts/test.sh
  Jenkinsfile
  dev-utils/docker-compose.yml
Labels: Team:Automation, automation, ci

#1044 chore: update elastic stack release version [7.13.2]
  Jenkinsfile
Labels: automation, dependency

#1048 fix: set stage result
  Jenkinsfile
Labels: bug
