Repository elastic/apm-agent-rum-js, pull requests merged in 2023-02, with the labels that each got.

#1336 chore: update elastic stack release version 8.6.1 8.6.1
  .ci/scripts/load-testing.sh
  .ci/scripts/pull_and_build.sh
  .ci/scripts/test.sh
  Jenkinsfile
  dev-utils/docker-compose.yml
Labels: automation, dependency

#1340 chore: bump elastic stack
  .ci/bump-elastic-stack.yml
  .ci/bump-stack-release-version.sh
  .github/workflows/bump-elastic-stack.yml
  .github/workflows/opentelemetry.yml
  Jenkinsfile
Labels: automation, Team:Automation

#1341 chore: use composite updatecli github action
  .github/workflows/bump-elastic-stack.yml
Labels: automation
